# fly.toml app configuration file generated for velocity-renderer on 2025-12-04T18:41:47+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'velocity-renderer'
primary_region = 'bom'

[build]

[deploy]
  strategy = 'rolling'
  wait_timeout = '5m0s'

[env]
  MALLOC_ARENA_MAX = '2'
  SPRING_PROFILES_ACTIVE = 'prod'
  TZ = 'UTC'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '1m0s'
    method = 'GET'
    path = '/actuator/health/readiness'

  [[http_service.checks]]
    interval = '1m0s'
    timeout = '3s'
    grace_period = '1m30s'
    method = 'GET'
    path = '/actuator/health/liveness'

[[restart]]
  policy = 'on-failure'
  retries = 3

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
